[package]
name = "plotter"
version = "0.1.0"
edition = "2021"
default-run = "plotter"

[dependencies]
syn = "2.0.66"
egui = "0.26.2"
eframe = "0.26.2"
egui-snarl = "0.3.0"
svg = "0.17.0"
nalgebra-glm = "0.18.0"
rand = "0.8.5"
statrs = "0.16.0"
tiny-skia = "0.11.4"
